import { addDays, format } from "date-fns";
import { formatReference } from "@/lib/utils/reference";
import type { TeamMember, TeamSummary } from "./summary";

const day = (offset: number) => format(addDays(new Date(), offset), "yyyy-MM-dd");
const at = (offset: number, time: string) => `${day(offset)}T${time}`;
const project = (seq: number) => formatReference("project", 2026, seq);

const empty: Pick<TeamMember, "metrics" | "projects" | "activity" | "skills"> = {
  metrics: { deliveredProjects: 0, revenue: 0, activeProjects: 0, openTasks: 0 },
  projects: [],
  activity: [],
  skills: [],
};

/**
 * Equipe de exemplo para o bloco do painel enquanto as métricas não existem no banco. Os membros de
 * verdade já moram em `organization_members`; o que falta são os números por pessoa, que nascem com
 * projetos e cobranças. Ninguém tem foto, para o rosto gerado pelo `Avatar` aparecer; o faturamento vai em
 * centavos, como todo dinheiro do produto.
 */
export const previewTeamSummary: TeamSummary = {
  members: [
    {
      id: "m1",
      name: "Aleph Ramos",
      role: "Desenvolvedor full stack",
      avatarUrl: null,
      status: "active",
      access: "owner",
      email: "aleph@specular.app",
      phone: "11991234567",
      city: "São Paulo, SP",
      joinedAt: day(-420),
      bio: "Fundou a equipe e cuida do produto de ponta a ponta. Prefere resolver pelo código antes de abrir reunião, e responde no WhatsApp fora do horário só para urgência.",
      points: 4_820,
      skills: ["Next.js", "TypeScript", "Postgres", "Design de interface"],
      metrics: { deliveredProjects: 9, revenue: 12_480_000, activeProjects: 3, openTasks: 7 },
      projects: [
        { id: "p11", reference: project(11), name: "Site institucional", status: "ongoing", progress: 62 },
        { id: "p7", reference: project(7), name: "Design system", status: "ongoing", progress: 48 },
        { id: "p4", reference: project(4), name: "Identidade visual", status: "done", progress: 100 },
      ],
      activity: [
        { id: "e1", action: "publicou a versão de homologação do site institucional", at: at(0, "09:40") },
        { id: "e2", action: "aprovou o orçamento ORC-2026-0044", at: at(-1, "16:20") },
        { id: "e3", action: "fechou 12 tarefas do design system", at: at(-3, "18:05") },
      ],
    },
    {
      id: "m2",
      name: "Adam Pires",
      role: "Redator",
      avatarUrl: null,
      status: "active",
      access: "member",
      email: "adam@specular.app",
      phone: "11992345678",
      city: "Campinas, SP",
      joinedAt: day(-260),
      bio: "Escreve os textos dos sites e das propostas. Gosta de receber o briefing por escrito antes da primeira conversa.",
      points: 1_940,
      skills: ["UX writing", "SEO", "Propostas"],
      metrics: { deliveredProjects: 4, revenue: 3_150_000, activeProjects: 2, openTasks: 3 },
      projects: [
        { id: "p11", reference: project(11), name: "Site institucional", status: "ongoing", progress: 62 },
        { id: "p9", reference: project(9), name: "Site da Bravo", status: "ongoing", progress: 80 },
      ],
      activity: [
        { id: "e1", action: "entregou os textos do site da Bravo", at: at(-1, "11:30") },
        { id: "e2", action: "revisou a proposta da Padaria Aurora", at: at(-2, "15:10") },
      ],
    },
    {
      id: "m3",
      name: "Arthur Gomes",
      role: "Líder de design",
      avatarUrl: null,
      status: "active",
      access: "admin",
      email: "arthur@specular.app",
      phone: "21993456789",
      city: "Rio de Janeiro, RJ",
      joinedAt: day(-390),
      bio: "Lidera o design e revisa tudo o que sai para cliente. Responsável pelo design system e pelas diretrizes de marca.",
      points: 4_110,
      skills: ["Figma", "Design system", "Identidade visual", "Motion"],
      metrics: { deliveredProjects: 7, revenue: 8_920_000, activeProjects: 2, openTasks: 5 },
      projects: [
        { id: "p7", reference: project(7), name: "Design system", status: "ongoing", progress: 48 },
        { id: "p4", reference: project(4), name: "Identidade visual", status: "done", progress: 100 },
      ],
      activity: [
        { id: "e1", action: "levou os cantos do design system para a superelipse", at: at(-1, "16:05") },
        { id: "e2", action: "aprovou a prévia do site institucional", at: at(-2, "10:15") },
      ],
    },
    {
      id: "m4",
      name: "Ana Freitas",
      role: "Front-end",
      avatarUrl: null,
      status: "active",
      access: "member",
      email: "ana@specular.app",
      phone: "31994567890",
      city: "Belo Horizonte, MG",
      joinedAt: day(-200),
      bio: "Monta as telas a partir do design e cuida da acessibilidade. Está estudando animação de interface.",
      points: 2_560,
      skills: ["React", "CSS", "Acessibilidade"],
      metrics: { deliveredProjects: 5, revenue: 4_600_000, activeProjects: 2, openTasks: 4 },
      projects: [
        { id: "p11", reference: project(11), name: "Site institucional", status: "ongoing", progress: 62 },
        { id: "p6", reference: project(6), name: "Manutenção do site", status: "ongoing", progress: 45 },
      ],
      activity: [
        { id: "e1", action: "testou o formulário de contato do site institucional", at: at(0, "11:02") },
        { id: "e2", action: "corrigiu o contraste dos botões no tema escuro", at: at(-2, "14:40") },
      ],
    },
    {
      id: "m5",
      name: "Bruno Sales",
      role: "Comercial",
      avatarUrl: null,
      status: "active",
      access: "member",
      email: "bruno@specular.app",
      phone: "41995678901",
      city: "Curitiba, PR",
      joinedAt: day(-310),
      bio: "Fecha os contratos e acompanha os clientes depois da entrega. Traz a maior parte das indicações.",
      points: 3_380,
      skills: ["Vendas", "Negociação", "Relacionamento"],
      metrics: { deliveredProjects: 2, revenue: 15_300_000, activeProjects: 1, openTasks: 6 },
      projects: [{ id: "p9", reference: project(9), name: "Site da Bravo", status: "ongoing", progress: 80 }],
      activity: [
        { id: "e1", action: "enviou o orçamento ORC-2026-0045 para a Padaria Aurora", at: at(-2, "09:12") },
        { id: "e2", action: "cadastrou a cliente Camila Ferreira", at: at(-1, "08:30") },
      ],
    },
    {
      id: "m6",
      name: "Carla Mendes",
      role: "Gestora de projetos",
      avatarUrl: null,
      status: "active",
      access: "admin",
      email: "carla@specular.app",
      phone: "51996789012",
      city: "Porto Alegre, RS",
      joinedAt: day(-350),
      bio: "Organiza os prazos e distribui as tarefas. É quem fala com o cliente quando algo atrasa.",
      points: 3_970,
      skills: ["Gestão de projetos", "Prazos", "Atendimento"],
      metrics: { deliveredProjects: 12, revenue: 11_750_000, activeProjects: 4, openTasks: 9 },
      projects: [
        { id: "p11", reference: project(11), name: "Site institucional", status: "ongoing", progress: 62 },
        { id: "p9", reference: project(9), name: "Site da Bravo", status: "ongoing", progress: 80 },
        { id: "p3", reference: project(3), name: "Site do escritório", status: "paused", progress: 90 },
      ],
      activity: [
        { id: "e1", action: "criou a tarefa Entrega do site institucional", at: at(-2, "15:00") },
        { id: "e2", action: "pausou o projeto do escritório a pedido da cliente", at: at(-5, "17:25") },
      ],
    },
    {
      id: "m7",
      name: "Diego Rocha",
      role: "Motion designer",
      avatarUrl: null,
      status: "pending",
      access: "member",
      email: "diego.rocha@gmail.com",
      phone: null,
      joinedAt: day(-2),
      points: 0,
      ...empty,
    },
    {
      id: "m8",
      name: "Elisa Martins",
      role: "UX writer",
      avatarUrl: null,
      status: "active",
      access: "member",
      email: "elisa@specular.app",
      phone: "61997890123",
      city: "Brasília, DF",
      joinedAt: day(-120),
      bio: "Cuida dos textos de interface e das mensagens de erro. Entrou pelo projeto da Dong Design.",
      points: 1_210,
      skills: ["UX writing", "Microtexto", "Pesquisa"],
      metrics: { deliveredProjects: 3, revenue: 2_280_000, activeProjects: 1, openTasks: 2 },
      projects: [{ id: "p7", reference: project(7), name: "Design system", status: "ongoing", progress: 48 }],
      activity: [{ id: "e1", action: "revisou os textos de erro dos formulários", at: at(-1, "13:50") }],
    },
  ],
};
