# Arquivos desta varredura, para separar do que a outra sessao mexeu.
#
# O tree tem 295 arquivos alterados: a maior parte e a remocao do sistema de superelipse e as features
# novas (formularios, feedbacks, aprovacoes, cronometro) da outra sessao, que ainda estao em andamento.
# Estes 94 sao os desta varredura.
#
# Para preparar so eles:
#   bash scripts/tmp-stage-varredura.sh

set -e

git add "db/migrations/finance/20260922031500_charge_quote_once.sql"
git add "db/migrations/organizations/20260922121500_release_current_org_on_member_removal.sql"
git add "db/migrations/quotes/20260922150000_quote_client_buys.sql"
git add "scripts/probe-session.mjs"
git add "src/app/(app)/cobrancas/[id]/page.tsx"
git add "src/app/(app)/despesas/nova/page.tsx"
git add "src/app/(public)/cobranca/[token]/page.tsx"
git add "src/app/api/v1/organizacoes/membros/route.ts"
git add "src/app/api/v1/tarefas/etapas/route.ts"
git add "src/app/componentes/demos.tsx"
git add "src/app/componentes/page.tsx"
git add "src/components/layout/notifications/index.tsx"
git add "src/components/layout/page-skeleton/page-skeleton.module.css"
git add "src/components/layout/page-toolbar/index.tsx"
git add "src/components/layout/sidebar/index.tsx"
git add "src/components/layout/sidebar/nav-tree.module.css"
git add "src/components/layout/sidebar/nav-tree.tsx"
git add "src/components/ui/details-dialog/index.tsx"
git add "src/components/ui/dialog/index.tsx"
git add "src/components/ui/dropdown-menu/index.tsx"
git add "src/components/ui/name-dialog/index.tsx"
git add "src/components/ui/sheet-switcher/index.tsx"
git add "src/components/ui/sheet-switcher/sheet-switcher.module.css"
git add "src/components/ui/stage-settings/index.tsx"
git add "src/docs/history.md"
git add "src/docs/structure.md"
git add "src/features/ai/service.ts"
git add "src/features/automations/components/automation-editor.tsx"
git add "src/features/automations/components/automations-board.tsx"
git add "src/features/automations/components/new-automation-dialog.tsx"
git add "src/features/automations/components/run-log-dialog.tsx"
git add "src/features/automations/service.ts"
git add "src/features/billing/components/plan-dialog.tsx"
git add "src/features/billing/components/plan-gate.tsx"
git add "src/features/billing/service.ts"
git add "src/features/catalog/components/catalog-board.tsx"
git add "src/features/catalog/components/catalog-form-dialog.tsx"
git add "src/features/catalog/service.ts"
git add "src/features/clients/components/client-drawer.tsx"
git add "src/features/clients/components/client-form-dialog.module.css"
git add "src/features/clients/components/client-form-dialog.tsx"
git add "src/features/clients/components/client-sections.tsx"
git add "src/features/clients/components/clients-board.module.css"
git add "src/features/clients/components/clients-board.tsx"
git add "src/features/clients/list-options.ts"
git add "src/features/clients/load-client.tsx"
git add "src/features/clients/queries.ts"
git add "src/features/clients/schemas.ts"
git add "src/features/clients/service.ts"
git add "src/features/contracts/components/contract-card.tsx"
git add "src/features/contracts/components/contracts-board.tsx"
git add "src/features/contracts/components/new-contract-dialog.tsx"
git add "src/features/contracts/service.ts"
git add "src/features/finance/components/charge-card.tsx"
git add "src/features/finance/components/charge-menu.tsx"
git add "src/features/finance/components/charges-board.tsx"
git add "src/features/finance/components/finance-overview.module.css"
git add "src/features/finance/components/finance-overview.tsx"
git add "src/features/finance/components/new-charge-dialog.tsx"
git add "src/features/finance/components/transaction-form-dialog.tsx"
git add "src/features/finance/components/transaction-receipt.tsx"
git add "src/features/finance/labels.ts"
git add "src/features/finance/queries.ts"
git add "src/features/finance/schemas.ts"
git add "src/features/finance/service.ts"
git add "src/features/finance/summary.ts"
git add "src/features/organizations/actions.ts"
git add "src/features/organizations/components/create-team-panel.tsx"
git add "src/features/organizations/components/team-people.tsx"
git add "src/features/organizations/service.ts"
git add "src/features/projects/components/project-editor.tsx"
git add "src/features/projects/components/project-form-dialog.tsx"
git add "src/features/projects/components/projects-board.tsx"
git add "src/features/projects/labels.ts"
git add "src/features/projects/service.ts"
git add "src/features/quotes/components/quote-editor.tsx"
git add "src/features/quotes/components/quotes-board.tsx"
git add "src/features/quotes/components/quotes-table.tsx"
git add "src/features/quotes/service.ts"
git add "src/features/records/components/history-dialog.tsx"
git add "src/features/records/components/relation-map-dialog.module.css"
git add "src/features/records/components/relation-map-dialog.tsx"
git add "src/features/settings/components/notifications-settings.tsx"
git add "src/features/settings/components/team-settings.tsx"
git add "src/features/settings/service.ts"
git add "src/features/tasks/components/task-add-dialogs.tsx"
git add "src/features/tasks/components/task-opener.tsx"
git add "src/features/tasks/components/tasks-board.tsx"
git add "src/features/tasks/service.ts"
git add "src/hooks/use-opened-once.ts"
git add "src/hooks/use-tab-list.ts"
git add "src/lib/db/message.ts"
git add "src/lib/utils/day.ts"
git add "src/lib/utils/site.ts"

echo "preparados: $(git diff --cached --name-only | wc -l)"
