import { addDays, format } from "date-fns";
import { formatReference } from "@/lib/utils/reference";
import type { ClientsSummary } from "./summary";

const day = (offset: number) => format(addDays(new Date(), offset), "yyyy-MM-dd");
const ref = (kind: "client" | "quote" | "project", seq: number) => formatReference(kind, 2026, seq);

/**
 * Resumo de exemplo enquanto o domínio não existe no banco. Quem montar a tabela troca só a origem: o
 * bloco recebe o resumo por prop e não sabe de onde ele vem. Ninguém tem foto, para o rosto gerado pelo
 * `Avatar` aparecer; o telefone vai só em dígitos, como no banco.
 */
export const previewClientsSummary: ClientsSummary = {
  total: 60,
  clients: [
    {
      id: "c1",
      reference: ref("client", 26),
      name: "Camila Ferreira",
      email: "camila@estudioaurora.com.br",
      phone: "11987654321",
      avatarUrl: null,
      createdAt: day(-1),
      company: "Estúdio Aurora",
      role: "Design de interiores",
      city: "São Paulo, SP",
      website: "https://estudioaurora.com.br",
      about:
        "Chegou por indicação da Linda. Quer um site institucional com portfólio de projetos e um formulário de contato simples. Prefere conversar pelo WhatsApp e responde rápido durante a tarde.",
      tags: ["Site institucional", "Portfólio", "Indicação"],
      active: true,
      favorite: true,
      stats: { quotes: 2, projects: 1, billed: 450_000, open: 320_000 },
      quotes: [
        { id: "q12", number: ref("quote", 44), title: "Site institucional com portfólio", amount: 770_000, status: "approved", date: day(-1) },
        { id: "q11", number: ref("quote", 41), title: "Identidade visual do estúdio", amount: 380_000, status: "viewed", date: day(-4) },
      ],
      projects: [{ id: "p11", reference: ref("project", 11), name: "Site institucional", status: "ongoing", progress: 62 }],
    },
    {
      id: "c2",
      reference: ref("client", 25),
      name: "Rafael Nunes",
      email: "rafael.nunes@bravo.studio",
      phone: "21998877665",
      avatarUrl: null,
      createdAt: day(-3),
      company: "Bravo Studio",
      role: "Produtora de vídeo",
      city: "Rio de Janeiro, RJ",
      website: "https://bravo.studio",
      about: "Precisa de um site rápido para a produtora, com os vídeos em destaque. Paga em três parcelas e pediu nota a cada uma.",
      tags: ["Site institucional", "Parcelado"],
      active: true,
      favorite: false,
      stats: { quotes: 1, projects: 1, billed: 640_000, open: 320_000 },
      quotes: [{ id: "q10", number: ref("quote", 39), title: "Site da produtora", amount: 960_000, status: "approved", date: day(-20) }],
      projects: [{ id: "p9", reference: ref("project", 9), name: "Site da Bravo", status: "ongoing", progress: 80 }],
    },
    {
      id: "c3",
      reference: ref("client", 24),
      name: "Marina Duarte",
      email: "marina@padariaaurora.com",
      phone: "31988776655",
      avatarUrl: null,
      createdAt: day(-6),
      company: "Padaria Aurora",
      role: "Padaria e confeitaria",
      city: "Belo Horizonte, MG",
      about: "Quer cardápio com fotos e pedidos pelo WhatsApp. Está comparando com outra agência, então a proposta precisa sair antes da reunião de sexta.",
      tags: ["Cardápio", "Pedidos", "Em negociação"],
      active: true,
      favorite: false,
      stats: { quotes: 1, projects: 0, billed: 0, open: 180_000 },
      quotes: [{ id: "q13", number: ref("quote", 45), title: "Site com cardápio e pedidos", amount: 540_000, status: "sent", date: day(-2) }],
      projects: [],
    },
    {
      id: "c4",
      reference: ref("client", 23),
      name: "Linda Dong",
      email: "linda@dong.design",
      phone: "4133445566",
      avatarUrl: null,
      createdAt: day(-9),
      company: "Dong Design",
      role: "Consultoria de marca",
      city: "Curitiba, PR",
      website: "https://dong.design",
      about: "Cliente antiga que indica outros clientes. A identidade visual foi entregue e aprovada; a manutenção mensal segue ativa.",
      tags: ["Identidade visual", "Manutenção", "Indica clientes"],
      active: true,
      favorite: true,
      stats: { quotes: 3, projects: 2, billed: 1_230_000, open: 0 },
      quotes: [
        { id: "q8", number: ref("quote", 31), title: "Manutenção mensal", amount: 180_000, status: "approved", date: day(-40) },
        { id: "q7", number: ref("quote", 27), title: "Identidade visual", amount: 450_000, status: "approved", date: day(-90) },
        { id: "q6", number: ref("quote", 22), title: "Papelaria completa", amount: 220_000, status: "declined", date: day(-120) },
      ],
      projects: [
        { id: "p4", reference: ref("project", 4), name: "Identidade visual", status: "done", progress: 100 },
        { id: "p6", reference: ref("project", 6), name: "Manutenção do site", status: "ongoing", progress: 45 },
      ],
    },
    {
      id: "c5",
      reference: ref("client", 22),
      name: "Tiago Almeida",
      email: "tiago@almeidaeng.com.br",
      phone: "51997766554",
      avatarUrl: null,
      createdAt: day(-12),
      company: "Almeida Engenharia",
      role: "Engenharia civil",
      city: "Porto Alegre, RS",
      tags: ["Landing page"],
      active: true,
      favorite: false,
      stats: { quotes: 1, projects: 0, billed: 0, open: 0 },
      quotes: [{ id: "q9", number: ref("quote", 35), title: "Landing page de captação", amount: 290_000, status: "expired", date: day(-30) }],
      projects: [],
    },
    {
      id: "c6",
      reference: ref("client", 21),
      name: "Beatriz Rocha",
      email: "bia@rochaadvocacia.com",
      phone: "61996655443",
      avatarUrl: null,
      createdAt: day(-15),
      company: "Rocha Advocacia",
      role: "Escritório de advocacia",
      city: "Brasília, DF",
      tags: ["Site institucional"],
      active: false,
      favorite: false,
      stats: { quotes: 1, projects: 1, billed: 380_000, open: 0 },
      quotes: [{ id: "q5", number: ref("quote", 18), title: "Site do escritório", amount: 380_000, status: "approved", date: day(-150) }],
      projects: [{ id: "p3", reference: ref("project", 3), name: "Site do escritório", status: "paused", progress: 90 }],
    },
  ],
};
